name: React CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build react app production version
        run: npm run build
      - name: Delete old build
        run: rm -rf /var/sr-apps/sr-production/dist
      - name: Move new build to production dir
        run: mv dist /var/sr-apps/sr-production
      - name: Restart pm2 process
        run: pm2 restart 1
